server:
  port: 8080
  servlet:
    context-path: /booking-app
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/booking_app"
    username: root
    password: 03092003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true