server:
  port: 8080
  servlet:
    context-path: /booking-app
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/booking_app"
    username: root
    password: 03092003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signer-key: "4AEDiq/xZcnqW7vryody9FTkI2droddl/Kw3FdvUkj6FKuNco86S0y1R567jIfLE"
  valid-duration: 86400 # in second
  refreshable-duration: 864000